import { Rule } from "../Parser/Types";
import { CompilationError, CompilerPass } from "./CompilerPass";
export declare type Checker = (rules: Rule[]) => CompilationError[];
export declare const check: (...checkers: Checker[]) => CompilerPass;
export declare const checkArity: Checker;
export declare const isLeftLinear: ([lhs, _]: Rule) => boolean;
export declare const checkLeftLinearity: Checker;
export declare const hasFreeVars: ([lhs, rhs]: Rule) => boolean;
export declare const checkNoFreeVars: Checker;
export declare const checkNoDuplicates: Checker;
export declare const allChecks: CompilerPass;
